version: '3.8'

services:
  hdhr-ac4:
    image: hdhr:latest
    ports:
      - "80:80"
      - "5004:5004"
    environment:
      HDHR_IP: "10.0.0.152"
      HOST_IP: "10.0.0.151"
      DEVICEID_SWAP: "1"
      XDG_RUNTIME_DIR: "/tmp"
#      FFMPEG_ARGS: "-nostats -hide_banner -loglevel warning -i pipe: -map 0:v -map 0:a -c:v copy -c:a ac3 -f mpegts -"
      FFMPEG_ARGS: "-nostats -hide_banner -loglevel warning -i pipe: -map 0:v -map 0:a -c:v h264_qsv -crf 23 -preset medium -c:a copy -f mpegts -"
#    volumes:
#      - /data/mnt/docker/hdhr-ac4/config:/config
    devices:
      - /dev/dri:/dev/dri
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true
    entrypoint: [""]  # Clear the existing ENTRYPOINT
    command: ["node", "index.js"]  # Run node index.js

    networks:
      mac_01:
        ipv4_address: 10.0.0.151

networks:
  mac_01:
    external: true
